from functools import lru_cache

from graph_rag_poc.models import GraphEdge, GraphNode, UseCase


@lru_cache(maxsize=1)
def get_demo_use_case() -> UseCase:
    nodes = (
        GraphNode(
            id="org_northwind",
            kind="Organization",
            name="Northwind Manufacturing",
            description="Synthetic industrial manufacturer used as the demo victim organization.",
            aliases=("northwind", "northwind manufacturing"),
            tags=("victim", "manufacturing", "demo"),
            stage="context",
            metadata={"sector": "manufacturing", "region": "EU"},
        ),
        GraphNode(
            id="incident_nw_2026_041",
            kind="Incident",
            name="NW-2026-041 Ransomware Investigation",
            description="Synthetic incident tying initial access, PowerShell execution, lateral movement, exfiltration, and ransomware impact into a single investigation.",
            aliases=("nw-2026-041", "northwind april incident"),
            tags=("incident", "ransomware", "graph-rag"),
            stage="impact",
            metadata={"severity": "critical", "status": "contained"},
        ),
        GraphNode(
            id="actor_night_lantern",
            kind="ThreatActor",
            name="Night Lantern",
            description="Synthetic extortion-focused cluster known for exploiting edge appliances, living-off-the-land PowerShell, and fast impact operations.",
            aliases=("night lantern", "synthetic extortion cluster"),
            tags=("threat-actor", "extortion", "ransomware"),
            stage="context",
            metadata={"confidence": "medium", "origin": "synthetic"},
        ),
        GraphNode(
            id="campaign_operation_night_lantern",
            kind="Campaign",
            name="Operation Night Lantern",
            description="Synthetic campaign showing a public-facing exploit on the VPN gateway, a pivot to a jump host, and eventual ransomware on the file server.",
            aliases=("operation night lantern", "night lantern campaign"),
            tags=("campaign", "intrusion-chain", "teachable"),
            stage="context",
            metadata={"window": "2026-04-03 to 2026-04-04"},
        ),
        GraphNode(
            id="product_panos_globalprotect",
            kind="Product",
            name="Palo Alto PAN-OS GlobalProtect",
            description="Public-facing VPN and remote access stack deployed on the edge gateway.",
            aliases=("pan-os", "globalprotect"),
            tags=("vpn", "edge", "remote-access"),
            stage="initial-access",
            metadata={"vendor": "Palo Alto Networks"},
        ),
        GraphNode(
            id="vuln_cve_2024_3400",
            kind="Vulnerability",
            name="CVE-2024-3400",
            description="Command injection vulnerability affecting PAN-OS GlobalProtect that can provide initial access on exposed gateways.",
            aliases=("cve-2024-3400",),
            tags=("cve", "initial-access", "edge-exploit"),
            stage="initial-access",
            metadata={"severity": "critical", "cvss": "10.0"},
        ),
        GraphNode(
            id="asset_vpn_gw_01",
            kind="Asset",
            name="vpn-gw-01",
            description="Northwind's public-facing VPN gateway that terminates remote access traffic.",
            aliases=("vpn gateway", "gateway", "vpn-gw-01"),
            tags=("asset", "internet-facing", "vpn"),
            stage="initial-access",
            metadata={"os": "PAN-OS", "criticality": "high"},
        ),
        GraphNode(
            id="asset_jump_01",
            kind="Asset",
            name="jump-01",
            description="Internal administrative jump host used by operations and IT administrators.",
            aliases=("jump-01", "jump host"),
            tags=("asset", "admin", "pivot"),
            stage="execution",
            metadata={"os": "Windows Server", "criticality": "high"},
        ),
        GraphNode(
            id="asset_fs_02",
            kind="Asset",
            name="fs-02",
            description="Critical file server hosting finance and production share data.",
            aliases=("fs-02", "file server"),
            tags=("asset", "fileserver", "impact"),
            stage="impact",
            metadata={"os": "Windows Server", "criticality": "critical"},
        ),
        GraphNode(
            id="technique_t1190",
            kind="Technique",
            name="T1190 Exploit Public-Facing Application",
            description="ATT&CK technique covering exploitation of exposed applications to gain initial access.",
            aliases=("t1190", "exploit public-facing application"),
            tags=("mitre", "initial-access"),
            stage="initial-access",
            metadata={"framework": "MITRE ATT&CK"},
        ),
        GraphNode(
            id="technique_t1059_001",
            kind="Technique",
            name="T1059.001 PowerShell",
            description="ATT&CK technique for executing commands and scripts via PowerShell.",
            aliases=("t1059.001", "powershell"),
            tags=("mitre", "execution"),
            stage="execution",
            metadata={"framework": "MITRE ATT&CK"},
        ),
        GraphNode(
            id="technique_t1078",
            kind="Technique",
            name="T1078 Valid Accounts",
            description="ATT&CK technique for abusing valid accounts instead of deploying noisy custom tooling.",
            aliases=("t1078", "valid accounts"),
            tags=("mitre", "credential-access"),
            stage="credential-access",
            metadata={"framework": "MITRE ATT&CK"},
        ),
        GraphNode(
            id="technique_t1021_001",
            kind="Technique",
            name="T1021.001 Remote Desktop Protocol",
            description="ATT&CK technique for lateral movement by abusing RDP connectivity.",
            aliases=("t1021.001", "rdp"),
            tags=("mitre", "lateral-movement"),
            stage="lateral-movement",
            metadata={"framework": "MITRE ATT&CK"},
        ),
        GraphNode(
            id="technique_t1567_002",
            kind="Technique",
            name="T1567.002 Exfiltration to Cloud Storage",
            description="ATT&CK technique for staging and exfiltrating data to attacker-controlled cloud storage.",
            aliases=("t1567.002", "cloud exfiltration"),
            tags=("mitre", "exfiltration"),
            stage="exfiltration",
            metadata={"framework": "MITRE ATT&CK"},
        ),
        GraphNode(
            id="technique_t1486",
            kind="Technique",
            name="T1486 Data Encrypted for Impact",
            description="ATT&CK technique describing ransomware-style encryption that disrupts business operations.",
            aliases=("t1486", "ransomware encryption"),
            tags=("mitre", "impact"),
            stage="impact",
            metadata={"framework": "MITRE ATT&CK"},
        ),
        GraphNode(
            id="alert_edge_exploit",
            kind="Alert",
            name="GlobalProtect exploit alert",
            description="IDS and firewall telemetry show exploit attempts and post-exploitation webshell-like behavior on vpn-gw-01.",
            aliases=("vpn exploit alert", "globalprotect exploit"),
            tags=("alert", "initial-access", "ids"),
            stage="initial-access",
            metadata={"severity": "critical", "source": "IDS"},
        ),
        GraphNode(
            id="alert_powershell_encoded",
            kind="Alert",
            name="Encoded PowerShell on jump-01",
            description="EDR raised an alert for encoded PowerShell and suspicious script block logging on the administrative jump host.",
            aliases=("powershell alert", "encoded powershell"),
            tags=("alert", "execution", "edr"),
            stage="execution",
            metadata={"severity": "high", "source": "EDR"},
        ),
        GraphNode(
            id="alert_valid_account_abuse",
            kind="Alert",
            name="svc-backup valid account abuse",
            description="The svc-backup account authenticated from jump-01 to multiple internal systems outside its normal maintenance window.",
            aliases=("valid account alert", "svc-backup abuse"),
            tags=("alert", "credential-access", "identity"),
            stage="credential-access",
            metadata={"severity": "high", "source": "Identity logs"},
        ),
        GraphNode(
            id="alert_rdp_lateral",
            kind="Alert",
            name="RDP lateral movement to fs-02",
            description="RDP session from jump-01 to fs-02 occurred shortly before archive creation and encryption activity.",
            aliases=("rdp alert", "lateral movement alert"),
            tags=("alert", "lateral-movement", "windows"),
            stage="lateral-movement",
            metadata={"severity": "high", "source": "Windows events"},
        ),
        GraphNode(
            id="alert_cloud_exfil",
            kind="Alert",
            name="Archive upload to cloud storage",
            description="Large encrypted archives were uploaded from fs-02 to an unapproved cloud storage destination.",
            aliases=("exfil alert", "cloud storage alert"),
            tags=("alert", "exfiltration", "network"),
            stage="exfiltration",
            metadata={"severity": "critical", "source": "Proxy"},
        ),
        GraphNode(
            id="alert_ransomware_impact",
            kind="Alert",
            name="Rapid encryption on fs-02",
            description="EDR and file integrity monitoring detected rapid rename-and-encrypt activity on the critical file server.",
            aliases=("ransomware alert", "encryption alert"),
            tags=("alert", "impact", "edr"),
            stage="impact",
            metadata={"severity": "critical", "source": "EDR"},
        ),
        GraphNode(
            id="control_patch_gateway",
            kind="Control",
            name="Patch or isolate the VPN gateway",
            description="Apply the vendor remediation for PAN-OS or isolate the GlobalProtect interface to close the initial access path.",
            aliases=("patch gateway", "vpn patch"),
            tags=("control", "containment", "initial-access"),
            stage="mitigation",
            metadata={"priority": "P0"},
        ),
        GraphNode(
            id="control_isolate_jump",
            kind="Control",
            name="Isolate jump-01 and collect volatile evidence",
            description="Contain the jump host before additional credential theft or remote execution can occur.",
            aliases=("isolate jump host", "contain jump-01"),
            tags=("control", "containment", "execution"),
            stage="mitigation",
            metadata={"priority": "P0"},
        ),
        GraphNode(
            id="control_reset_accounts",
            kind="Control",
            name="Disable svc-backup and rotate privileged credentials",
            description="Reset abused credentials and review any other service accounts exposed through the same path.",
            aliases=("disable svc-backup", "reset credentials"),
            tags=("control", "identity", "credential-reset"),
            stage="mitigation",
            metadata={"priority": "P0"},
        ),
        GraphNode(
            id="control_block_egress",
            kind="Control",
            name="Block malicious egress and preserve exfiltration evidence",
            description="Block the identified cloud destination and capture network evidence before attackers switch infrastructure.",
            aliases=("block egress", "stop exfiltration"),
            tags=("control", "network", "exfiltration"),
            stage="mitigation",
            metadata={"priority": "P1"},
        ),
        GraphNode(
            id="doc_ir_report",
            kind="Document",
            name="Incident response timeline",
            description="Internal timeline linking the edge exploit, PowerShell execution, account abuse, RDP pivot, exfiltration, and encryption.",
            aliases=("ir report", "timeline"),
            tags=("document", "investigation"),
            stage="context",
            metadata={"owner": "IR team"},
        ),
        GraphNode(
            id="doc_vendor_advisory",
            kind="Document",
            name="Vendor advisory for CVE-2024-3400",
            description="Public advisory summarizing the PAN-OS GlobalProtect issue and recommended remediation actions.",
            aliases=("vendor advisory", "cve advisory"),
            tags=("document", "advisory"),
            stage="context",
            metadata={"owner": "Vendor"},
        ),
        GraphNode(
            id="doc_containment_playbook",
            kind="Document",
            name="Ransomware containment playbook",
            description="Internal playbook prioritizing isolation, identity response, egress blocking, and executive communications.",
            aliases=("containment playbook", "playbook"),
            tags=("document", "response"),
            stage="mitigation",
            metadata={"owner": "SOC"},
        ),
    )

    edges = (
        GraphEdge("incident_nw_2026_041", "org_northwind", "AFFECTS", "The investigation concerns Northwind Manufacturing.", 1.0),
        GraphEdge("incident_nw_2026_041", "campaign_operation_night_lantern", "INVOLVES", "The incident is attributed to the synthetic campaign.", 1.0),
        GraphEdge("campaign_operation_night_lantern", "actor_night_lantern", "ATTRIBUTED_TO", "The campaign is associated with Night Lantern.", 1.0),
        GraphEdge("campaign_operation_night_lantern", "vuln_cve_2024_3400", "EXPLOITS", "Initial access came through the exposed PAN-OS issue.", 1.2),
        GraphEdge("campaign_operation_night_lantern", "technique_t1190", "USES", "The campaign used an exploit against a public-facing application.", 1.1),
        GraphEdge("campaign_operation_night_lantern", "technique_t1059_001", "USES", "The campaign used PowerShell on the jump host.", 1.0),
        GraphEdge("campaign_operation_night_lantern", "technique_t1078", "USES", "The campaign abused a valid service account.", 1.0),
        GraphEdge("campaign_operation_night_lantern", "technique_t1021_001", "USES", "The campaign pivoted with RDP.", 1.0),
        GraphEdge("campaign_operation_night_lantern", "technique_t1567_002", "USES", "The campaign staged exfiltration to cloud storage.", 1.0),
        GraphEdge("campaign_operation_night_lantern", "technique_t1486", "USES", "The campaign encrypted data for impact.", 1.0),
        GraphEdge("org_northwind", "asset_vpn_gw_01", "OWNS", "Northwind owns the VPN gateway.", 0.9),
        GraphEdge("org_northwind", "asset_jump_01", "OWNS", "Northwind owns the administrative jump host.", 0.9),
        GraphEdge("org_northwind", "asset_fs_02", "OWNS", "Northwind owns the critical file server.", 0.9),
        GraphEdge("asset_vpn_gw_01", "product_panos_globalprotect", "RUNS", "The edge gateway runs PAN-OS GlobalProtect.", 1.0),
        GraphEdge("vuln_cve_2024_3400", "product_panos_globalprotect", "AFFECTS", "The CVE affects PAN-OS GlobalProtect.", 1.1),
        GraphEdge("asset_vpn_gw_01", "asset_jump_01", "CONNECTS_TO", "The attacker pivoted from the edge gateway toward the jump host.", 0.8),
        GraphEdge("asset_jump_01", "asset_fs_02", "CONNECTS_TO", "The jump host has administrative reachability to the file server.", 0.8),
        GraphEdge("technique_t1190", "technique_t1059_001", "PRECEDES", "Initial access led to interactive command execution.", 1.0),
        GraphEdge("technique_t1059_001", "technique_t1078", "PRECEDES", "PowerShell activity preceded credential or account abuse.", 1.0),
        GraphEdge("technique_t1078", "technique_t1021_001", "PRECEDES", "Valid account abuse enabled RDP movement.", 1.0),
        GraphEdge("technique_t1021_001", "technique_t1567_002", "PRECEDES", "Lateral movement led to data staging and exfiltration.", 0.9),
        GraphEdge("technique_t1567_002", "technique_t1486", "PRECEDES", "Exfiltration was followed by encryption for impact.", 0.9),
        GraphEdge("alert_edge_exploit", "asset_vpn_gw_01", "OBSERVED_ON", "Exploit telemetry was observed on the VPN gateway.", 1.2),
        GraphEdge("alert_edge_exploit", "vuln_cve_2024_3400", "INDICATES", "The edge alert aligns with the PAN-OS CVE.", 1.2),
        GraphEdge("alert_edge_exploit", "technique_t1190", "INDICATES", "The edge alert indicates public-facing exploitation.", 1.1),
        GraphEdge("alert_powershell_encoded", "asset_jump_01", "OBSERVED_ON", "Encoded PowerShell occurred on jump-01.", 1.1),
        GraphEdge("alert_powershell_encoded", "technique_t1059_001", "INDICATES", "The alert indicates PowerShell execution.", 1.1),
        GraphEdge("alert_valid_account_abuse", "asset_jump_01", "OBSERVED_ON", "The service account activity originated from jump-01.", 1.0),
        GraphEdge("alert_valid_account_abuse", "technique_t1078", "INDICATES", "The alert indicates abuse of a valid account.", 1.1),
        GraphEdge("alert_rdp_lateral", "asset_fs_02", "OBSERVED_ON", "The RDP pivot reached the file server.", 1.0),
        GraphEdge("alert_rdp_lateral", "technique_t1021_001", "INDICATES", "The alert indicates RDP movement.", 1.1),
        GraphEdge("alert_cloud_exfil", "asset_fs_02", "OBSERVED_ON", "The exfiltration activity occurred from fs-02.", 1.1),
        GraphEdge("alert_cloud_exfil", "technique_t1567_002", "INDICATES", "The alert indicates cloud-storage exfiltration.", 1.1),
        GraphEdge("alert_ransomware_impact", "asset_fs_02", "OBSERVED_ON", "The ransomware activity impacted fs-02.", 1.2),
        GraphEdge("alert_ransomware_impact", "technique_t1486", "INDICATES", "The alert indicates encryption for impact.", 1.2),
        GraphEdge("incident_nw_2026_041", "alert_edge_exploit", "EVIDENCED_BY", "The incident is evidenced by the edge exploit alert.", 1.0),
        GraphEdge("incident_nw_2026_041", "alert_powershell_encoded", "EVIDENCED_BY", "The incident is evidenced by encoded PowerShell.", 1.0),
        GraphEdge("incident_nw_2026_041", "alert_valid_account_abuse", "EVIDENCED_BY", "The incident is evidenced by valid account abuse.", 1.0),
        GraphEdge("incident_nw_2026_041", "alert_rdp_lateral", "EVIDENCED_BY", "The incident is evidenced by RDP movement.", 1.0),
        GraphEdge("incident_nw_2026_041", "alert_cloud_exfil", "EVIDENCED_BY", "The incident is evidenced by exfiltration.", 1.0),
        GraphEdge("incident_nw_2026_041", "alert_ransomware_impact", "EVIDENCED_BY", "The incident is evidenced by encryption activity.", 1.0),
        GraphEdge("control_patch_gateway", "vuln_cve_2024_3400", "MITIGATES", "Patching or isolating the gateway removes the exploit path.", 1.2),
        GraphEdge("control_patch_gateway", "technique_t1190", "MITIGATES", "The gateway control limits exploitation of the public interface.", 1.1),
        GraphEdge("control_isolate_jump", "technique_t1059_001", "MITIGATES", "Isolating the jump host disrupts further PowerShell execution.", 1.1),
        GraphEdge("control_reset_accounts", "technique_t1078", "MITIGATES", "Credential reset disrupts valid-account abuse.", 1.2),
        GraphEdge("control_reset_accounts", "technique_t1021_001", "MITIGATES", "Credential reset weakens RDP lateral movement.", 1.0),
        GraphEdge("control_block_egress", "technique_t1567_002", "MITIGATES", "Egress controls disrupt cloud storage exfiltration.", 1.1),
        GraphEdge("doc_ir_report", "incident_nw_2026_041", "DESCRIBES", "The IR report describes the end-to-end incident timeline.", 0.9),
        GraphEdge("doc_ir_report", "alert_edge_exploit", "REFERENCES", "The IR timeline references the VPN exploit alert.", 0.8),
        GraphEdge("doc_ir_report", "alert_ransomware_impact", "REFERENCES", "The IR timeline references the ransomware impact.", 0.8),
        GraphEdge("doc_vendor_advisory", "vuln_cve_2024_3400", "DESCRIBES", "The advisory documents the PAN-OS issue.", 0.9),
        GraphEdge("doc_containment_playbook", "control_patch_gateway", "RECOMMENDS", "The playbook recommends gateway containment.", 0.8),
        GraphEdge("doc_containment_playbook", "control_isolate_jump", "RECOMMENDS", "The playbook recommends isolating the jump host.", 0.8),
        GraphEdge("doc_containment_playbook", "control_reset_accounts", "RECOMMENDS", "The playbook recommends identity response.", 0.8),
        GraphEdge("doc_containment_playbook", "control_block_egress", "RECOMMENDS", "The playbook recommends blocking suspicious egress.", 0.8),
    )

    return UseCase(
        id="operation-night-lantern",
        title="Operation Night Lantern",
        description="A synthetic but realistic ransomware investigation that demonstrates why graph-aware retrieval is useful in cybersecurity workflows.",
        learning_goals=(
            "Show how Graph RAG links alerts, techniques, assets, and controls into one investigation graph.",
            "Demonstrate the difference between graph-aware retrieval and vector-only retrieval.",
            "Provide a cybersecurity use case that both data scientists and security analysts can inspect.",
        ),
        storyline=(
            "Night Lantern exploits a vulnerable GlobalProtect gateway via CVE-2024-3400.",
            "The attacker pivots to jump-01 and executes encoded PowerShell.",
            "A valid service account is abused to move laterally over RDP to fs-02.",
            "Data is archived and exfiltrated to cloud storage.",
            "Ransomware encrypts fs-02, disrupting finance and production shares.",
            "Containment focuses on gateway remediation, jump-host isolation, credential rotation, and egress blocking.",
        ),
        suggested_questions=(
            "How are the VPN exploit alerts connected to the ransomware on fs-02?",
            "Why does Graph RAG produce a stronger investigation than vector-only retrieval here?",
            "What should the SOC do in the next four hours to contain Operation Night Lantern?",
            "Which ATT&CK techniques link the initial exploit to the business-impact event?",
        ),
        nodes=nodes,
        edges=edges,
    )

